// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type Application struct {
	ID          int64     `json:"id"`
	CandidateID int64     `json:"candidate_id"`
	JobID       int64     `json:"job_id"`
	Status      string    `json:"status"`
	Message     string    `json:"message"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
}
