// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	AssociateEmployerWithEnterprise(ctx context.Context, arg AssociateEmployerWithEnterpriseParams) error
	// Optional pagination
	CreateEmployerProfile(ctx context.Context, arg CreateEmployerProfileParams) (EmployerProfile, error)
	GetEmployerOne(ctx context.Context, id int64) (EmployerProfile, error)
	GetEmployerProfileByEnterpriseID(ctx context.Context, enterpriseID int64) (EmployerProfile, error)
	ListEmployerProfiles(ctx context.Context, arg ListEmployerProfilesParams) ([]EmployerProfile, error)
	UpdateEmailConfirmed(ctx context.Context, email string) error
	UpdateEmployerProfile(ctx context.Context, arg UpdateEmployerProfileParams) (EmployerProfile, error)
}

var _ Querier = (*Queries)(nil)
