// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	GetApplication(ctx context.Context, id int64) (Application, error)
	ListApplications(ctx context.Context, arg ListApplicationsParams) ([]Application, error)
	UpdateStatusApplication(ctx context.Context, arg UpdateStatusApplicationParams) (Application, error)
}

var _ Querier = (*Queries)(nil)
