name: backend-employer-service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'
    - run: go version

    - name: Install-Golang-Dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Test
      run: make test

    - name: Build
      run: go build -o main main.go
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: nguyenthuanit265/backend-employer-service:latest

    - name: Transfer Docker image to remote server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      
    - name: Run remove docker container backend-employer-service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
        docker stop backend-jobstreet-employer-service-prod backend-jobstreet-employer-service-prod-1 backend-jobstreet-employer-service-prod-2 backend-jobstreet-employer-service-prod-3
        docker rm -f backend-jobstreet-employer-service-prod backend-jobstreet-employer-service-prod-1 backend-jobstreet-employer-service-prod-2 backend-jobstreet-employer-service-prod-3
        docker rmi -f nguyenthuanit265/backend-employer-service:latest
        ENDSSH

      # docker run --name backend-jobstreet-employer-service-prod --network jobstreet-network -p 4001:4001 -e DB_SOURCE="postgresql://${{secrets.POSTGRES_USER_DB_EMPLOYER}}:${{secrets.POSTGRES_PASSWORD_DB_EMPLOYER}}@${{secrets.REMOTE_SERVER_ADDRESS}}:5432/employer_service_jobstreet?sslmode=disable" -d nguyenthuanit265/backend-employer-service:latest
      # docker run --name backend-jobstreet-employer-service-prod-1 --network jobstreet-network -p 5001:4001 -e CONTAINER_ID=Container-1 -e DB_SOURCE="postgresql://admin:admin@postgres:5432/employer_service_jobstreet?sslmode=disable" -d nguyenthuanit265/backend-employer-service:latest
      # docker run --name backend-jobstreet-employer-service-prod-2 --network jobstreet-network -p 5002:4001 -e CONTAINER_ID=Container-2 -e DB_SOURCE="postgresql://admin:admin@postgres:5432/employer_service_jobstreet?sslmode=disable" -d nguyenthuanit265/backend-employer-service:latest
      # docker run --name backend-jobstreet-employer-service-prod-3 --network jobstreet-network -p 5003:4001 -e CONTAINER_ID=Container-3 -e DB_SOURCE="postgresql://admin:admin@postgres:5432/employer_service_jobstreet?sslmode=disable" -d nguyenthuanit265/backend-employer-service:latest
    - name: Run docker container backend-employer-service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
        docker run --name backend-jobstreet-employer-service-prod-1 --network jobstreet-network -p 5001:4001 -e DB_SOURCE="postgresql://${{secrets.POSTGRES_USER_DB_EMPLOYER}}:${{secrets.POSTGRES_PASSWORD_DB_EMPLOYER}}@${{secrets.REMOTE_SERVER_ADDRESS}}:5432/employer_service_jobstreet?sslmode=disable" -e CONTAINER_ID=Container-1 -d nguyenthuanit265/backend-employer-service:latest
        docker run --name backend-jobstreet-employer-service-prod-2 --network jobstreet-network -p 5002:4001 -e DB_SOURCE="postgresql://${{secrets.POSTGRES_USER_DB_EMPLOYER}}:${{secrets.POSTGRES_PASSWORD_DB_EMPLOYER}}@${{secrets.REMOTE_SERVER_ADDRESS}}:5432/employer_service_jobstreet?sslmode=disable" -e CONTAINER_ID=Container-2 -d nguyenthuanit265/backend-employer-service:latest
        docker run --name backend-jobstreet-employer-service-prod-3 --network jobstreet-network -p 5003:4001 -e DB_SOURCE="postgresql://${{secrets.POSTGRES_USER_DB_EMPLOYER}}:${{secrets.POSTGRES_PASSWORD_DB_EMPLOYER}}@${{secrets.REMOTE_SERVER_ADDRESS}}:5432/employer_service_jobstreet?sslmode=disable" -e CONTAINER_ID=Container-3 -d nguyenthuanit265/backend-employer-service:latest
        ENDSSH
